# Docker Compose for ClaudeGraph Neo4j

services:
  neo4j:
    image: neo4j:5.15
    container_name: claudegraph-neo4j
    ports:
      - "7475:7474"  # Web UI (shifted to avoid conflict)
      - "7688:7687"  # Bolt protocol (shifted to avoid conflict)
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./ontology:/import/ontology
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "claudegraph", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local